discourse:
  repo_path: ../discourse

screenshot:
  devices: desktop
  dir: ../discourse/tmp/theme-screenshots-github
  width: 2560
  height: 1440
  format: png
  max_bytes: 1048576

themes:
  - id: foundation
    name: Foundation
    source:
      type: core
      theme: foundation
    modes: [light]
  - id: horizon
    name: Horizon
    source:
      type: core
      theme: horizon
    modes: [light]
  - id: mint-theme
    name: Mint Theme
    source:
      type: git
      url: https://github.com/Discourse/discourse-mint-theme.git
    modes: [light]
  - id: minima
    name: Minima
    source:
      type: git
      url: https://github.com/Discourse/minima.git
    modes: [light]
  - id: material
    name: Material Design Theme
    source:
      type: git
      url: https://github.com/discourse/material-design-stock-theme.git
    modes: [light]
  - id: discourse-air
    name: Air THeme
    source:
      type: git
      url: https://github.com/discourse/discourse-air.git
  - id: discourse-verso
    name: Verso
    source:
      type: git
      url: https://github.com/pmusaraj/discourse-verso.git
    modes: [light]
  - id: discourse-summit
    name: Summit
    source:
      type: git
      url: https://github.com/pmusaraj/discourse-summit.git
    modes: [light]
  - id: discourse-finline
    name: Finline
    source:
      type: git
      url: https://github.com/pmusaraj/discourse-finline.git
    modes: [light]
  - id: discourse-accent
    name: Accent
    source:
      type: git
      url: https://github.com/pmusaraj/discourse-accent.git
    modes: [light]
